# Generated by Django 5.2.13 on 2026-04-23 06:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='ID во внешней системе')),
                ('source_system', models.CharField(choices=[('manual', 'Создано вручную'), ('1c_bp', '1С:Бухгалтерия предприятия'), ('1c_do', '1С:Документооборот'), ('mock_1c', 'Mock-1C')], default='manual', max_length=32, verbose_name='Источник')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('exists_in_one_c', models.BooleanField(default=True, verbose_name='Есть в 1С:БП')),
                ('is_internal_turnover', models.BooleanField(default=False, verbose_name='ВГО')),
            ],
            options={
                'verbose_name': 'Статья ДДС',
                'verbose_name_plural': 'Статьи ДДС',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='ID во внешней системе')),
                ('source_system', models.CharField(choices=[('manual', 'Создано вручную'), ('1c_bp', '1С:Бухгалтерия предприятия'), ('1c_do', '1С:Документооборот'), ('mock_1c', 'Mock-1C')], default='manual', max_length=32, verbose_name='Источник')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='ID во внешней системе')),
                ('source_system', models.CharField(choices=[('manual', 'Создано вручную'), ('1c_bp', '1С:Бухгалтерия предприятия'), ('1c_do', '1С:Документооборот'), ('mock_1c', 'Mock-1C')], default='manual', max_length=32, verbose_name='Источник')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'ЦФО',
                'verbose_name_plural': 'ЦФО',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='ID во внешней системе')),
                ('source_system', models.CharField(choices=[('manual', 'Создано вручную'), ('1c_bp', '1С:Бухгалтерия предприятия'), ('1c_do', '1С:Документооборот'), ('mock_1c', 'Mock-1C')], default='manual', max_length=32, verbose_name='Источник')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('can_create_manually', models.BooleanField(default=True, verbose_name='Можно создавать вручную')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='ID во внешней системе')),
                ('source_system', models.CharField(choices=[('manual', 'Создано вручную'), ('1c_bp', '1С:Бухгалтерия предприятия'), ('1c_do', '1С:Документооборот'), ('mock_1c', 'Mock-1C')], default='manual', max_length=32, verbose_name='Источник')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='mock_1c', max_length=64, verbose_name='Поставщик')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка')], max_length=16, verbose_name='Статус')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='Статистика')),
            ],
            options={
                'verbose_name': 'Запуск синхронизации',
                'verbose_name_plural': 'Запуски синхронизации',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='ID во внешней системе')),
                ('source_system', models.CharField(choices=[('manual', 'Создано вручную'), ('1c_bp', '1С:Бухгалтерия предприятия'), ('1c_do', '1С:Документооборот'), ('mock_1c', 'Mock-1C')], default='manual', max_length=32, verbose_name='Источник')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('can_create_manually', models.BooleanField(default=True, verbose_name='Можно создавать вручную')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'inn'), name='uniq_counterparty_name_inn')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='ID во внешней системе')),
                ('source_system', models.CharField(choices=[('manual', 'Создано вручную'), ('1c_bp', '1С:Бухгалтерия предприятия'), ('1c_do', '1С:Документооборот'), ('mock_1c', 'Mock-1C')], default='manual', max_length=32, verbose_name='Источник')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('number', models.CharField(max_length=64, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('kind', models.CharField(choices=[('customer', 'Договор с покупателем'), ('sole_supplier', 'Договор с единственным поставщиком')], max_length=32, verbose_name='Тип договора')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма')),
                ('manual_exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Ручной курс валюты')),
                ('parent_customer_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_contracts', to='core.contract', verbose_name='Доходный договор')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.counterparty', verbose_name='Контрагент')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='ID во внешней системе')),
                ('source_system', models.CharField(choices=[('manual', 'Создано вручную'), ('1c_bp', '1С:Бухгалтерия предприятия'), ('1c_do', '1С:Документооборот'), ('mock_1c', 'Mock-1C')], default='manual', max_length=32, verbose_name='Источник')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('number', models.CharField(max_length=64, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_agreements', to='core.contract', verbose_name='Договор')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Дополнительное соглашение',
                'verbose_name_plural': 'Дополнительные соглашения',
                'ordering': ['date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='ID во внешней системе')),
                ('source_system', models.CharField(choices=[('manual', 'Создано вручную'), ('1c_bp', '1С:Бухгалтерия предприятия'), ('1c_do', '1С:Документооборот'), ('mock_1c', 'Mock-1C')], default='manual', max_length=32, verbose_name='Источник')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('date', models.DateField(verbose_name='Дата')),
                ('account', models.CharField(max_length=2, verbose_name='Счет учета')),
                ('direction', models.CharField(choices=[('inflow', 'Поступление денежных средств'), ('outflow', 'Списание денежных средств')], max_length=16, verbose_name='Направление')),
                ('accounting_kind', models.CharField(choices=[('bu', 'БУ'), ('nu', 'НУ')], max_length=8, verbose_name='Вид учета')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cashflowarticle', verbose_name='Статья ДДС')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.counterparty', verbose_name='Контрагент')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Факт оплаты',
                'verbose_name_plural': 'Факты оплат',
                'ordering': ['date', 'external_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('kind', 'number', 'date'), name='uniq_contract_kind_number_date'),
        ),
        migrations.AddConstraint(
            model_name='additionalagreement',
            constraint=models.UniqueConstraint(fields=('contract', 'number', 'date'), name='uniq_agreement_contract_number_date'),
        ),
        migrations.AddConstraint(
            model_name='paymentfact',
            constraint=models.UniqueConstraint(fields=('external_id', 'accounting_kind'), name='uniq_payment_fact_external_accounting'),
        ),
    ]
