# Generated by Django 5.2.13 on 2026-04-23 06:23

import django.core.validators
from django.db import migrations, models


def create_default_theme(apps, schema_editor):
    UiThemeSettings = apps.get_model('core', 'UiThemeSettings')
    UiThemeSettings.objects.create(name='1C Light Blue', is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1C Light Blue', max_length=120, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('primary_color', models.CharField(default='#1b75d0', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основной синий')),
                ('primary_hover', models.CharField(default='#155fa9', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Синий при наведении')),
                ('primary_soft', models.CharField(default='#e7f2ff', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Светло-голубой акцент')),
                ('background_color', models.CharField(default='#f3f7fc', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон приложения')),
                ('surface_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон рабочей области')),
                ('sidebar_color', models.CharField(default='#eef5fc', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон бокового меню')),
                ('border_color', models.CharField(default='#d7e4f2', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Линии и границы')),
                ('text_color', models.CharField(default='#20242a', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основной текст')),
                ('muted_text_color', models.CharField(default='#6d7785', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Вторичный текст')),
                ('warning_color', models.CharField(default='#ffce3a', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Предупреждение')),
                ('danger_color', models.CharField(default='#d92d20', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Ошибка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка палитры интерфейса',
                'verbose_name_plural': 'Настройки палитры интерфейса',
            },
        ),
        migrations.RunPython(create_default_theme, migrations.RunPython.noop),
    ]
