# Generated by Django 5.2.13 on 2026-04-23 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uithemesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Просмотр'), ('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('approve', 'Утверждение'), ('login', 'Вход'), ('denied', 'Отказ доступа')], max_length=32, verbose_name='Действие')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='Путь')),
                ('method', models.CharField(blank=True, max_length=12, verbose_name='Метод')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP-статус')),
                ('object_type', models.CharField(blank=True, max_length=120, verbose_name='Тип объекта')),
                ('object_id', models.CharField(blank=True, max_length=120, verbose_name='ID объекта')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действия',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Администратор'), ('economist', 'Экономист'), ('manager', 'Руководитель'), ('accountant', 'Бухгалтер')], max_length=32, verbose_name='Роль')),
                ('is_app_access_enabled', models.BooleanField(default=True, verbose_name='Доступ к системе включен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='ЦФО')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
