# Generated by Django 5.2.13 on 2026-04-23 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'Просмотр'), ('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('approve', 'Утверждение'), ('pay', 'Оплата'), ('login', 'Вход'), ('denied', 'Отказ доступа')], max_length=32, verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='ExternalPaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведен')], default='posted', max_length=16, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_payments', to=settings.AUTH_USER_MODEL, verbose_name='Бухгалтер')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_payments', to='core.contract', verbose_name='Договор')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта')),
                ('payment_fact_bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentfact', verbose_name='Факт БУ')),
                ('payment_fact_nu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentfact', verbose_name='Факт НУ')),
            ],
            options={
                'verbose_name': 'Внешняя оплата договора',
                'verbose_name_plural': 'Внешние оплаты договоров',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
