# Generated by Django 5.2.13 on 2026-04-23 07:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditlog_action_externalpaymentdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLimitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер документа')),
                ('document_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата документа')),
                ('planning_year', models.PositiveSmallIntegerField(verbose_name='Период планирования')),
                ('planning_horizon', models.PositiveSmallIntegerField(default=1, verbose_name='Горизонт планирования')),
                ('annual_amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма плана')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_approval', 'На утверждении'), ('approved', 'Утвержден'), ('closed', 'Закрыт')], default='draft', max_length=32, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('correction_reason', models.CharField(blank=True, max_length=255, verbose_name='Основание для корректировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_plans_to_approve', to=settings.AUTH_USER_MODEL, verbose_name='Утверждающий')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cashflowarticle', verbose_name='Статья ДДС')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_plans', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта плана')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department', verbose_name='ЦФО')),
            ],
            options={
                'verbose_name': 'План / лимит',
                'verbose_name_plural': 'Планы / лимиты',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLimitMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Сумма')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='core.budgetlimitplan', verbose_name='План / лимит')),
            ],
            options={
                'verbose_name': 'Строка помесячного плана',
                'verbose_name_plural': 'Строки помесячного плана',
                'ordering': ['month'],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetlimitplan',
            constraint=models.CheckConstraint(condition=models.Q(('planning_horizon__in', [1, 2, 3])), name='budget_plan_horizon_1_2_3'),
        ),
        migrations.AddConstraint(
            model_name='budgetlimitmonth',
            constraint=models.UniqueConstraint(fields=('plan', 'month'), name='uniq_budget_plan_month'),
        ),
        migrations.AddConstraint(
            model_name='budgetlimitmonth',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='budget_plan_month_1_12'),
        ),
    ]
