# Generated by Django 5.2.13 on 2026-04-23 07:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_budgetlimitplan_budgetlimitmonth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLimitAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер документа')),
                ('document_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата документа')),
                ('new_annual_amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Новая сумма')),
                ('reason', models.TextField(verbose_name='Причина корректировки')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_approval', 'На утверждении'), ('approved', 'Утвержден'), ('closed', 'Закрыт')], default='draft', max_length=32, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_adjustments_to_approve', to=settings.AUTH_USER_MODEL, verbose_name='Утверждающий')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cashflowarticle', verbose_name='Статья ДДС')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('base_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='core.budgetlimitplan', verbose_name='Базовый документ')),
            ],
            options={
                'verbose_name': 'Корректировка лимита',
                'verbose_name_plural': 'Корректировки лимитов',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLimitAdjustmentMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Сумма')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='core.budgetlimitadjustment', verbose_name='Корректировка лимита')),
            ],
            options={
                'verbose_name': 'Строка помесячной корректировки',
                'verbose_name_plural': 'Строки помесячной корректировки',
                'ordering': ['month'],
                'constraints': [models.UniqueConstraint(fields=('adjustment', 'month'), name='uniq_budget_adjustment_month'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='budget_adjustment_month_1_12')],
            },
        ),
    ]
