# Generated by Django 5.2.13 on 2026-04-23 11:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_budgetlimitadjustment_budgetlimitadjustmentmonth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequestControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Контроль лимитов заявок', max_length=120, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('control_mode', models.CharField(choices=[('warning', 'Предупреждение'), ('block', 'Блокировка')], default='warning', max_length=16, verbose_name='Режим контроля лимита')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка контроля лимита заявок',
                'verbose_name_plural': 'Настройки контроля лимита заявок',
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'Просмотр'), ('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('approve', 'Утверждение'), ('pay', 'Оплата'), ('transfer', 'Передача'), ('login', 'Вход'), ('denied', 'Отказ доступа')], max_length=32, verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('request_kind', models.CharField(choices=[('by_contract', 'По договору'), ('by_invoice', 'По счету'), ('without_contract', 'Без договора')], max_length=32, verbose_name='Тип заявки')),
                ('request_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата заявки')),
                ('invoice_number', models.CharField(blank=True, max_length=64, verbose_name='Счет')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма')),
                ('manual_exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Курс к RUB')),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма в RUB')),
                ('limit_remaining_before_rub', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Остаток лимита до заявки, RUB')),
                ('limit_remaining_after_rub', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Остаток лимита после заявки, RUB')),
                ('limit_exceeded', models.BooleanField(default=False, verbose_name='Превышение лимита')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_approval', 'На согласовании'), ('approved', 'Согласована'), ('transferred', 'Передана в 1С:ДО'), ('rejected', 'Отклонена')], default='draft', max_length=32, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласования')),
                ('transferred_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата передачи в 1С:ДО')),
                ('do_external_id', models.CharField(blank=True, max_length=64, verbose_name='ID в 1С:ДО')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests_to_approve', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cashflowarticle', verbose_name='Статья ДДС')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='core.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.counterparty', verbose_name='Контрагент')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Заявка на оплату',
                'verbose_name_plural': 'Заявки на оплату',
                'ordering': ['-request_date', '-created_at'],
            },
        ),
    ]
