# Generated by Django 5.2.13 on 2026-04-23 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymentrequestcontrolsettings_alter_auditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFactControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Контроль корректировок факта', max_length=120, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('closed_through', models.DateField(blank=True, null=True, verbose_name='Период закрыт по')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка закрытия периода по факту оплат',
                'verbose_name_plural': 'Настройки закрытия периода по факту оплат',
            },
        ),
        migrations.CreateModel(
            name='PaymentFactAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
                ('previous_amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма до корректировки')),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма после корректировки')),
                ('previous_comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий до корректировки')),
                ('new_comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий после корректировки')),
                ('reason', models.TextField(verbose_name='Причина корректировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_fact_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Автор корректировки')),
                ('payment_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='core.paymentfact', verbose_name='Факт оплаты')),
            ],
            options={
                'verbose_name': 'Корректировка факта оплаты',
                'verbose_name_plural': 'Корректировки факта оплаты',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('payment_fact', 'version'), name='uniq_payment_fact_adjustment_version')],
            },
        ),
    ]
