# Generated by Django 5.2.13 on 2026-04-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paymentfactcontrolsettings_paymentfactadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная')], default='light', max_length=16, verbose_name='Тема интерфейса'),
        ),
    ]
