# Generated by Django 5.2.13 on 2026-04-24 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_theme_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер заявки')),
                ('integration_name', models.CharField(max_length=120, verbose_name='Название интеграции')),
                ('target_system', models.CharField(max_length=120, verbose_name='Целевая система')),
                ('description', models.TextField(verbose_name='Описание потребности')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_integration_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный администратор')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_requests', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Заявка на интеграцию',
                'verbose_name_plural': 'Заявки на интеграцию',
                'ordering': ['-created_at'],
            },
        ),
    ]
