# Generated by Django 5.2.13 on 2026-04-27 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_integrationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='additional_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='core.additionalagreement', verbose_name='Допсоглашение'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='approver_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий согласующего'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата счета'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='justification_file',
            field=models.FileField(blank=True, upload_to='payment_requests/justifications/', verbose_name='Файл обоснования'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='justification_text',
            field=models.TextField(blank=True, verbose_name='Обоснование оплаты'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_purpose',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назначение платежа'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отклонения'),
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('report_type', models.CharField(choices=[('plan_fact', 'РџР»Р°РЅ-С„Р°РєС‚ Р‘Р”Р”РЎ')], max_length=32, verbose_name='Тип отчета')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Настройки фильтров')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'report_type', 'name'), name='uniq_report_template_owner_type_name')],
            },
        ),
    ]
