# Generated by Codex on 2026-05-18

import re

import core.validators
from django.db import migrations, models


def seed_document_sequences(apps, schema_editor):
    document_sequence = apps.get_model("core", "DocumentSequence")
    sources = [
        ("PL", apps.get_model("core", "BudgetLimitPlan"), "number"),
        ("ADJ", apps.get_model("core", "BudgetLimitAdjustment"), "number"),
        ("REQ", apps.get_model("core", "PaymentRequest"), "number"),
        ("DO", apps.get_model("core", "PaymentRequest"), "do_external_id"),
        ("BP", apps.get_model("core", "ExternalPaymentDocument"), "number"),
        ("INT", apps.get_model("core", "IntegrationRequest"), "number"),
    ]

    max_values = {}
    for prefix, model, field_name in sources:
        pattern = re.compile(rf"^{re.escape(prefix)}-(\d{{4}})-(\d+)$")
        for value in model.objects.exclude(**{field_name: ""}).values_list(field_name, flat=True):
            match = pattern.match(value or "")
            if not match:
                continue
            year = int(match.group(1))
            current = int(match.group(2))
            key = (prefix, year)
            max_values[key] = max(max_values.get(key, 0), current)

    for (prefix, year), current_value in max_values.items():
        document_sequence.objects.update_or_create(
            prefix=prefix,
            year=year,
            defaults={"current_value": current_value},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_paymentrequest_additional_agreement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="justification_file",
            field=models.FileField(
                blank=True,
                upload_to=core.validators.payment_request_justification_upload_to,
                validators=[core.validators.validate_justification_file],
                verbose_name="Файл обоснования",
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="report_type",
            field=models.CharField(
                choices=[("plan_fact", "План-факт БДДС")],
                max_length=32,
                verbose_name="Тип отчета",
            ),
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prefix", models.CharField(max_length=16, verbose_name="Префикс")),
                ("year", models.PositiveSmallIntegerField(verbose_name="Год")),
                ("current_value", models.PositiveIntegerField(default=0, verbose_name="Текущее значение")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Счетчик документов",
                "verbose_name_plural": "Счетчики документов",
                "ordering": ["prefix", "year"],
                "constraints": [
                    models.UniqueConstraint(fields=("prefix", "year"), name="uniq_document_sequence_prefix_year"),
                ],
            },
        ),
        migrations.RunPython(seed_document_sequences, migrations.RunPython.noop),
    ]
