# Generated by Codex on 2026-05-18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_documentsequence_harden_paymentrequest_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=32, unique=True, verbose_name="Номер бюджета")),
                ("document_date", models.DateField(default=django.utils.timezone.localdate, verbose_name="Дата документа")),
                ("budget_year", models.PositiveSmallIntegerField(verbose_name="Период бюджета")),
                (
                    "periodicity",
                    models.CharField(
                        choices=[("year", "Год")],
                        default="year",
                        max_length=16,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("overall", "Общий"), ("by_department", "По ЦФО")],
                        default="overall",
                        max_length=32,
                        verbose_name="Вид бюджета",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=16, verbose_name="Сумма бюджета")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending_approval", "На утверждении"),
                            ("approved", "Утвержден"),
                            ("closed", "Закрыт"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.currency",
                        verbose_name="Валюта бюджета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бюджет",
                "verbose_name_plural": "Бюджеты",
                "ordering": ["-document_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BudgetDepartmentAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16, verbose_name="Сумма бюджета ЦФО")),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_allocations",
                        to="core.budgetplan",
                        verbose_name="Бюджет",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.department",
                        verbose_name="ЦФО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка бюджета по ЦФО",
                "verbose_name_plural": "Строки бюджета по ЦФО",
                "ordering": ["department__code"],
                "constraints": [
                    models.UniqueConstraint(fields=("budget", "department"), name="uniq_budget_department_allocation"),
                ],
            },
        ),
        migrations.AddField(
            model_name="budgetlimitplan",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="limits",
                to="core.budgetplan",
                verbose_name="Бюджет",
            ),
        ),
    ]
