# Generated by Django 5.2.14 on 2026-05-19 05:07

import django.db.models.deletion
from django.db import migrations, models


def populate_budget_organizations(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    BudgetPlan = apps.get_model("core", "BudgetPlan")
    BudgetLimitPlan = apps.get_model("core", "BudgetLimitPlan")

    default_organization = Organization.objects.order_by("id").first()
    if default_organization is None:
        return

    BudgetPlan.objects.filter(organization__isnull=True).update(organization=default_organization)
    for plan in BudgetLimitPlan.objects.filter(organization__isnull=True).select_related("budget"):
        plan.organization = plan.budget.organization if plan.budget_id and plan.budget.organization_id else default_organization
        plan.save(update_fields=["organization"])


def clear_budget_organizations(apps, schema_editor):
    BudgetPlan = apps.get_model("core", "BudgetPlan")
    BudgetLimitPlan = apps.get_model("core", "BudgetLimitPlan")

    BudgetLimitPlan.objects.update(organization=None)
    BudgetPlan.objects.update(organization=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_budgetplan_split_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetlimitadjustment",
            name="target_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_limit_adjustments",
                to="core.organization",
                verbose_name="Компания-получатель",
            ),
        ),
        migrations.AddField(
            model_name="budgetlimitadjustment",
            name="target_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_adjustments",
                to="core.budgetlimitplan",
                verbose_name="Целевой лимит для межкомпанийного переноса",
            ),
        ),
        migrations.AddField(
            model_name="budgetlimitplan",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_limits",
                to="core.organization",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="budgetplan",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="core.organization",
                verbose_name="Компания",
            ),
        ),
        migrations.RunPython(populate_budget_organizations, clear_budget_organizations),
        migrations.AlterField(
            model_name="budgetlimitplan",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_limits",
                to="core.organization",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="budgetplan",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="core.organization",
                verbose_name="Компания",
            ),
        ),
    ]
