# Generated by Django 5.2.14 on 2026-05-21 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_budgetlimitadjustment_target_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment_submitted', 'Заявка ушла на согласование'), ('payment_approved', 'Заявка согласована'), ('payment_rejected', 'Заявка отклонена'), ('payment_transferred', 'Заявка передана в 1С:ДО'), ('budget_submitted', 'Бюджет на утверждении'), ('limit_submitted', 'Лимит на утверждении'), ('limit_approved', 'Лимит утверждён'), ('limit_adjustment_submitted', 'Корректировка лимита на утверждении'), ('limit_overrun', 'Превышение лимита'), ('external_payment_posted', 'Внешняя оплата проведена'), ('integration_status_changed', 'Статус интеграционной заявки изменён')], max_length=64, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=500, verbose_name='Текст')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('payload_object_type', models.CharField(blank=True, max_length=120, verbose_name='Тип объекта')),
                ('payload_object_id', models.CharField(blank=True, max_length=120, verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='core_notifi_recipie_43dea6_idx'), models.Index(fields=['-created_at'], name='core_notifi_created_f19d5e_idx')],
            },
        ),
    ]
