# Generated by Django 5.2.14 on 2026-05-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены автором'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_approval', 'На согласовании'), ('approved', 'Согласована'), ('transferred', 'Передана в 1С:ДО'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена автором')], default='draft', max_length=32, verbose_name='Статус'),
        ),
    ]
