# Generated by Django 5.2.14 on 2026-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_paymentrequest_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки на согласование'),
        ),
    ]
