# Generated by Django 5.2.14 on 2026-05-28 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_paymentrequest_submitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='escalation_threshold_rub',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Заявки на сумму ≥ порога после первого согласования уходят на финальное согласование', max_digits=16, null=True, verbose_name='Порог эскалации, RUB'),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_approver_for_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Финальный согласующий'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_approval', 'На согласовании'), ('pending_final_approval', 'На финальном согласовании'), ('approved', 'Согласована'), ('transferred', 'Передана в 1С:ДО'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена автором')], default='draft', max_length=32, verbose_name='Статус'),
        ),
    ]
