# Generated by Django 5.2.14 on 2026-05-28 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_organization_escalation_threshold_rub_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год планирования')),
                ('kind', models.CharField(choices=[('base', 'Базовый'), ('optimistic', 'Оптимистичный'), ('pessimistic', 'Пессимистичный'), ('custom', 'Пользовательский')], default='base', max_length=16, verbose_name='Тип')),
                ('is_baseline', models.BooleanField(default=False, help_text='Только один сценарий компании в году может быть базовым; используется в отчётах по умолчанию', verbose_name='Базовый для компании/года')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_scenarios', to='core.organization', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сценарий планирования',
                'verbose_name_plural': 'Сценарии планирования',
                'ordering': ['-year', 'organization__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='budgetlimitplan',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='core.planningscenario', verbose_name='Сценарий планирования'),
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='core.planningscenario', verbose_name='Сценарий планирования'),
        ),
        migrations.AddConstraint(
            model_name='planningscenario',
            constraint=models.UniqueConstraint(fields=('organization', 'year', 'name'), name='uniq_scenario_org_year_name'),
        ),
    ]
