# Generated by Django 5.2.14 on 2026-05-29 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_backfill_baseline_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowarticle',
            name='direction',
            field=models.CharField(choices=[('outflow', 'Выплаты'), ('inflow', 'Поступления'), ('internal', 'Внутренние обороты'), ('transfer', 'Переводы между счетами')], default='outflow', max_length=16, verbose_name='Направление потока'),
        ),
        migrations.AddField(
            model_name='cashflowarticle',
            name='is_group',
            field=models.BooleanField(default=False, help_text='True для статей-группировок; на группу нельзя списать деньги напрямую', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='cashflowarticle',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Группировка статей: операционные / инвестиционные / финансовые и т.д.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.cashflowarticle', verbose_name='Родительская статья (группа)'),
        ),
    ]
