# Generated by Django 5.2.14 on 2026-05-29 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cashflowarticle_direction_cashflowarticle_is_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Заполняется для kind=LOAN_RECEIVED / LOAN_GIVEN', max_digits=6, verbose_name='Процентная ставка (для займов), % годовых'),
        ),
        migrations.AddField(
            model_name='contract',
            name='maturity_date',
            field=models.DateField(blank=True, help_text='Заполняется для договоров займа', null=True, verbose_name='Дата возврата / погашения'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='kind',
            field=models.CharField(choices=[('customer', 'Договор с покупателем'), ('sole_supplier', 'Договор с единственным поставщиком'), ('loan_received', 'Договор займа (получен нами)'), ('loan_given', 'Договор займа (выдан нами)')], max_length=32, verbose_name='Тип договора'),
        ),
        migrations.CreateModel(
            name='FundingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название кейса')),
                ('description', models.TextField(blank=True, verbose_name='Описание / Цель')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'В работе'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], default='active', max_length=16, verbose_name='Статус')),
                ('opened_at', models.DateField(auto_now_add=True, verbose_name='Дата открытия кейса')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_cases', to='core.organization', verbose_name='Компания')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_funding_cases', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Кейс финансирования',
                'verbose_name_plural': 'Кейсы финансирования',
                'ordering': ['-opened_at', 'code'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='funding_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.fundingcase', verbose_name='Кейс финансирования'),
        ),
    ]
