# Generated by Django 5.2.14 on 2026-05-29 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_contract_interest_rate_contract_maturity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentfact',
            name='loan_interest_portion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сколько в этом возврате приходится на проценты (остальное — тело)', max_digits=16, verbose_name='Из них проценты по займу'),
        ),
        migrations.AddField(
            model_name='paymentfact',
            name='loan_repayment_contract',
            field=models.ForeignKey(blank=True, help_text='Указывается, когда этот OUTFLOW-факт целевой платёж по погашению конкретного займа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayment_facts', to='core.contract', verbose_name='Гасит заём'),
        ),
    ]
