# Generated by Django 5.2.14 on 2026-06-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_paymentfact_loan_interest_portion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingcase',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'В работе'), ('waiting_for_inflow', 'Ждём поступление'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], default='active', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('payment_submitted', 'Заявка ушла на согласование'), ('payment_approved', 'Заявка согласована'), ('payment_rejected', 'Заявка отклонена'), ('payment_transferred', 'Заявка передана в 1С:ДО'), ('budget_submitted', 'Бюджет на утверждении'), ('limit_submitted', 'Лимит на утверждении'), ('limit_approved', 'Лимит утверждён'), ('limit_adjustment_submitted', 'Корректировка лимита на утверждении'), ('limit_overrun', 'Превышение лимита'), ('loan_maturity_near', 'Приближается срок возврата займа'), ('external_payment_posted', 'Внешняя оплата проведена'), ('integration_status_changed', 'Статус интеграционной заявки изменён')], max_length=64, verbose_name='Тип'),
        ),
    ]
