# Generated by Django 5.2.14 on 2026-06-01 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_fundingcase_status_alter_notification_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField(verbose_name='Номер периода')),
                ('due_date', models.DateField(verbose_name='Дата платежа')),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Тело, к оплате')),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Проценты, к оплате')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Остаток тела после периода')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Оплачено по этой строке')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Дата фактической оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('loan_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_lines', to='core.contract', verbose_name='Договор займа')),
            ],
            options={
                'verbose_name': 'Строка графика платежей по займу',
                'verbose_name_plural': 'Строки графика платежей по займу',
                'ordering': ['loan_contract_id', 'period'],
                'indexes': [models.Index(fields=['loan_contract', 'due_date'], name='core_loansc_loan_co_8e5c7a_idx')],
                'constraints': [models.UniqueConstraint(fields=('loan_contract', 'period'), name='uniq_loan_schedule_period')],
            },
        ),
    ]
