# Generated by Django 5.2.14 on 2026-06-01 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_loanscheduleline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='audit_object_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentfact',
            index=models.Index(fields=['organization', 'date'], name='pf_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentfact',
            index=models.Index(fields=['contract', 'direction'], name='pf_contract_dir_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentfact',
            index=models.Index(fields=['article', 'date'], name='pf_article_date_idx'),
        ),
    ]
