# Generated by Django 5.2.14 on 2026-06-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auditlog_audit_object_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц (1-12)')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата закрытия')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата открытия для правок')),
                ('unlock_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина повторного открытия')),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_locks', to=settings.AUTH_USER_MODEL, verbose_name='Кто закрыл')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_locks', to='core.organization', verbose_name='Организация')),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='period_unlocks', to=settings.AUTH_USER_MODEL, verbose_name='Кто открыл')),
            ],
            options={
                'verbose_name': 'Закрытие учётного периода',
                'verbose_name_plural': 'Закрытия учётных периодов',
                'ordering': ['-year', '-month', 'organization__name'],
                'indexes': [models.Index(fields=['organization', 'year', 'month'], name='period_lock_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'year', 'month'), name='uniq_period_lock_org_year_month')],
            },
        ),
    ]
