# Generated by Django 5.2.14 on 2026-06-01 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_accountingperiodlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(verbose_name='Дата курса')),
                ('rate_to_rub', models.DecimalField(decimal_places=6, help_text='Сколько RUB за единицу валюты на эту дату', max_digits=14, verbose_name='Курс к RUB')),
                ('source', models.CharField(choices=[('manual', 'Введён вручную'), ('cbr', 'ЦБ РФ'), ('internal', 'Внутренний (учётная политика)')], default='manual', max_length=16, verbose_name='Источник')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', to='core.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-rate_date', 'currency__code'],
                'indexes': [models.Index(fields=['currency', '-rate_date'], name='exchange_rate_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('currency', 'rate_date', 'source'), name='uniq_exchange_rate_curr_date_src')],
            },
        ),
    ]
