# Generated by Django 5.2.14 on 2026-06-01 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_exchangerate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('method', models.CharField(choices=[('percent', 'Фиксированные проценты'), ('equal', 'Равные доли')], default='percent', max_length=16, verbose_name='Метод распределения')),
                ('target_pct', models.JSONField(default=dict, help_text='Формат: {"<department_id>": <процент>}, сумма = 100.', verbose_name='Целевые доли (ЦФО → процент)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_rules_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_rules', to='core.organization', verbose_name='Организация')),
                ('source_article', models.ForeignKey(help_text='Факты по этой статье будут распределены', on_delete=django.db.models.deletion.PROTECT, related_name='allocation_rules', to='core.cashflowarticle', verbose_name='Статья-источник')),
            ],
            options={
                'verbose_name': 'Правило распределения',
                'verbose_name_plural': 'Правила распределения',
                'ordering': ['organization__name', 'name'],
            },
        ),
    ]
