# Generated by Django 5.2.14 on 2026-06-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_allocationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_holding_member',
            field=models.BooleanField(default=True, help_text='Если включено — компания входит в периметр консолидированной отчётности. Сделки с другими членами холдинга считаются ВГО и устраняются при консолидации.', verbose_name='Член холдинга'),
        ),
    ]
