# Generated by Django 5.2.14 on 2026-06-02 07:40

import core.models.funding
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_apitoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('event_type', models.CharField(choices=[('funding_case.status_changed', 'Смена статуса кейса'), ('funding_case.created', 'Создание кейса'), ('payment_fact.large', 'Крупный факт оплаты'), ('loan.maturity_due_soon', 'Приближение срока возврата займа')], max_length=64, verbose_name='Событие')),
                ('target_url', models.URLField(max_length=500, verbose_name='URL-приёмник')),
                ('secret', models.CharField(default=core.models.funding._gen_webhook_secret, help_text='Используется для подписи заголовка X-NEUX-Signature (HMAC-SHA256)', max_length=128, verbose_name='Секрет для HMAC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_fired_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка')),
                ('last_status_code', models.IntegerField(blank=True, null=True, verbose_name='Последний HTTP-код ответа')),
                ('failure_count', models.IntegerField(default=0, verbose_name='Подряд неудачных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Webhook-подписка',
                'verbose_name_plural': 'Webhook-подписки',
                'ordering': ['-created_at'],
            },
        ),
    ]
