# Generated by Django 5.2.14 on 2026-06-02 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_webhooksubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('applies_to_kind', models.CharField(choices=[('payment_request', 'Заявка на оплату'), ('budget_plan', 'Бюджет / лимит')], default='payment_request', max_length=32, verbose_name='Применяется к')),
                ('min_amount_rub', models.DecimalField(decimal_places=2, default=0, help_text='Документы с amount_rub ≥ этого значения попадают в цепочку', max_digits=16, verbose_name='Сумма от, RUB')),
                ('max_amount_rub', models.DecimalField(blank=True, decimal_places=2, help_text='Документы с amount_rub ≤ этого значения. Пусто = без верхней границы', max_digits=16, null=True, verbose_name='Сумма до, RUB')),
                ('stages', models.JSONField(default=list, help_text='JSON-список: [{"order": 1, "approver_username": "manager", "comment": "..."}]', verbose_name='Этапы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_chains_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_chains', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Цепочка согласования',
                'verbose_name_plural': 'Цепочки согласования',
                'ordering': ['organization__name', 'min_amount_rub'],
            },
        ),
    ]
