# Generated by Django 5.2.14 on 2026-06-02 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_approvalchain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Короткое имя для формул', max_length=64, verbose_name='Код')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год планирования')),
                ('kind', models.CharField(choices=[('volume', 'Объём'), ('price', 'Цена за единицу'), ('multiplier', 'Мультипликатор / коэффициент'), ('cost_per_unit', 'Переменная себестоимость'), ('fixed', 'Фиксированная сумма')], default='volume', max_length=20, verbose_name='Тип драйвера')),
                ('unit', models.CharField(blank=True, help_text='шт., т., ₽/шт., %', max_length=32, verbose_name='Единица')),
                ('monthly_values', models.JSONField(default=list, help_text='JSON-list из 12 чисел: январь..декабрь', verbose_name='Помесячные значения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_drivers_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_drivers', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Драйвер плана',
                'verbose_name_plural': 'Драйверы плана',
                'ordering': ['organization__name', '-year', 'kind', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('organization', 'year', 'code'), name='uniq_plan_driver_org_year_code')],
            },
        ),
    ]
