from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path

from core.views import (
    RoleAwareLoginView,
    audit_log,
    budget_limit_history,
    contracts_register,
    notification_follow,
    notifications,
    payment_fact_history,
    contracts_reservations,
    contracts_tree,
    document_action_wizard,
    external_accounting,
    external_payment_wizard,
    healthz,
    integration_requests,
    integration_request_status_wizard,
    integration_request_wizard,
    instruction,
    instruction_asset,
    limit_adjustment_wizard,
    manager_dashboard,
    counterparty_360,
    nsi_dashboard,
    nsi_directory,
    payment_fact_adjustment_wizard,
    payment_facts,
    payment_request_edit_wizard,
    payment_request_justification_download,
    payment_request_wizard,
    executive_dashboard,
    fx_revaluation_report,
    variance_analysis_report,
    global_search_view,
    exchange_rates,
    period_close,
    plan_fact_report,
    profit_loss_report,
    planning_budgets,
    funding_case_detail,
    funding_case_print,
    funding_cases_index,
    planning_scenarios,
    planning_template_builder,
    planning_wizard,
    set_working_organization,
    set_theme_mode,
    payment_requests,
    planning_limits,
    styleguide,
    workspace,
)


urlpatterns = [
    path("", workspace, name="workspace"),
    path("search/", global_search_view, name="global_search"),
    path(
        "workflow/<str:document_type>/<int:document_id>/<str:action>-wizard/",
        document_action_wizard,
        name="document_action_wizard",
    ),
    path("planning/wizard/", planning_wizard, name="planning_wizard"),
    path("planning/scenarios/", planning_scenarios, name="planning_scenarios"),
    path("planning/templates/", planning_template_builder, name="planning_template_builder"),
    path("funding/cases/", funding_cases_index, name="funding_cases_index"),
    path("funding/cases/<int:case_id>/", funding_case_detail, name="funding_case_detail"),
    path("funding/cases/<int:case_id>/print/", funding_case_print, name="funding_case_print"),
    path("planning/adjustments/wizard/", limit_adjustment_wizard, name="limit_adjustment_wizard"),
    path("planning/budgets/", planning_budgets, name="planning_budgets"),
    path("planning/limits/", planning_limits, name="planning_limits"),
    path("planning/limits/<int:plan_id>/history/", budget_limit_history, name="budget_limit_history"),
    path("payments/requests/wizard/", payment_request_wizard, name="payment_request_wizard"),
    path("payments/requests/<int:request_id>/edit-wizard/", payment_request_edit_wizard, name="payment_request_edit_wizard"),
    path(
        "payments/requests/<int:request_id>/justification/",
        payment_request_justification_download,
        name="payment_request_justification_download",
    ),
    path("payments/requests/", payment_requests, name="payment_requests"),
    path("payments/facts/wizard/", payment_fact_adjustment_wizard, name="payment_fact_adjustment_wizard"),
    path("payments/facts/<int:fact_id>/history/", payment_fact_history, name="payment_fact_history"),
    path("payments/facts/", payment_facts, name="payment_facts"),
    path("reports/manager/", manager_dashboard, name="manager_dashboard"),
    path("reports/plan-fact/", plan_fact_report, name="plan_fact_report"),
    path("reports/profit-loss/", profit_loss_report, name="profit_loss_report"),
    path("reports/executive/", executive_dashboard, name="executive_dashboard"),
    path("reports/fx-revaluation/", fx_revaluation_report, name="fx_revaluation_report"),
    path("reports/variance/", variance_analysis_report, name="variance_analysis_report"),
    path("contracts/register/", contracts_register, name="contracts_register"),
    path("contracts/reservations/", contracts_reservations, name="contracts_reservations"),
    path("contracts/tree/", contracts_tree, name="contracts_tree"),
    path("nsi/", nsi_dashboard, name="nsi_dashboard"),
    path("nsi/counterparties/<int:counterparty_id>/360/", counterparty_360, name="counterparty_360"),
    path("nsi/<str:directory>/", nsi_directory, name="nsi_directory"),
    path("external/accounting/", external_accounting, name="external_accounting"),
    path("external/accounting/payment-wizard/", external_payment_wizard, name="external_payment_wizard"),
    path("instruction/", instruction, name="instruction"),
    path("instruction/assets/<path:asset_path>", instruction_asset, name="instruction_asset"),
    path("login/", RoleAwareLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("settings/working-organization/", set_working_organization, name="set_working_organization"),
    path("settings/theme/", set_theme_mode, name="set_theme_mode"),
    path("settings/integration-requests/wizard/", integration_request_wizard, name="integration_request_wizard"),
    path(
        "settings/integration-requests/<int:request_id>/status-wizard/",
        integration_request_status_wizard,
        name="integration_request_status_wizard",
    ),
    path("settings/integration-requests/", integration_requests, name="integration_requests"),
    path("settings/period-close/", period_close, name="period_close"),
    path("settings/exchange-rates/", exchange_rates, name="exchange_rates"),
    path("settings/styleguide/", styleguide, name="styleguide"),
    path("settings/audit/", audit_log, name="audit_log"),
    path("notifications/", notifications, name="notifications"),
    path("notifications/<int:notification_id>/follow/", notification_follow, name="notification_follow"),
    path("healthz/", healthz, name="healthz"),
    path("admin/", admin.site.urls),
]
