from datetime import date
from decimal import Decimal

from core.models import AccountingKind, ContractKind, PaymentDirection

from .provider import (
    AdditionalAgreementDTO,
    CashFlowArticleDTO,
    ContractDTO,
    CounterpartyDTO,
    CurrencyDTO,
    DepartmentDTO,
    NomenclatureDTO,
    OneCDataset,
    OrganizationDTO,
    PaymentFactDTO,
)


class MockOneCProvider:
    def load_dataset(self) -> OneCDataset:
        return OneCDataset(
            currencies=[
                CurrencyDTO("cur-rub", "RUB", "Российский рубль"),
                CurrencyDTO("cur-usd", "USD", "Доллар США"),
                CurrencyDTO("cur-eur", "EUR", "Евро"),
            ],
            organizations=[
                OrganizationDTO("org-gladiolus", 'ООО "Гладиолус"', "7704555010"),
                OrganizationDTO("org-iris", 'ООО "Ирис"', "7704555020"),
            ],
            departments=[
                DepartmentDTO("dep-economy", "CFO-001", "Управление экономики"),
                DepartmentDTO("dep-admin", "CFO-002", "Администрация"),
            ],
            cash_flow_articles=[
                CashFlowArticleDTO("dds-ops", "DDS-010", "Оплата производственных услуг"),
                CashFlowArticleDTO("dds-rent", "DDS-020", "Аренда и эксплуатация"),
                CashFlowArticleDTO("dds-it", "DDS-030", "ИТ-сервисы и лицензии"),
                CashFlowArticleDTO("dds-vgo", "DDS-900", "Внутригрупповые обороты", is_internal_turnover=True),
                CashFlowArticleDTO("dds-manual", "DDS-MANUAL-001", "Разовая статья экономиста", exists_in_one_c=False),
            ],
            counterparties=[
                CounterpartyDTO("cp-buyer", 'АО "Северный покупатель"', "7801000001"),
                CounterpartyDTO("cp-supplier-1", 'ООО "МонтажСервис"', "7702000002"),
                CounterpartyDTO("cp-supplier-2", 'ООО "ИнфраЛизинг"', "7703000003"),
                CounterpartyDTO("cp-it", 'ООО "СофтПлатформа"', "7704000004"),
                CounterpartyDTO("cp-group", 'ООО "Группа Гладиолус"', "7705000005"),
            ],
            nomenclature=[
                NomenclatureDTO("nom-install", "NOM-001", "Монтажные работы"),
                NomenclatureDTO("nom-rent", "NOM-002", "Аренда оборудования"),
                NomenclatureDTO("nom-license", "NOM-003", "Корпоративная лицензия"),
            ],
            contracts=[
                ContractDTO(
                    external_id="ctr-customer-1",
                    number="ДП-2026-001",
                    date=date(2026, 1, 15),
                    name="Доходный договор на поставку оборудования",
                    kind=ContractKind.CUSTOMER,
                    counterparty_external_id="cp-buyer",
                    currency_code="RUB",
                    amount=Decimal("12500000.00"),
                ),
                ContractDTO(
                    external_id="ctr-supplier-1",
                    number="ЕП-2026-014",
                    date=date(2026, 2, 1),
                    name="Монтаж оборудования по проекту ДП-2026-001",
                    kind=ContractKind.SOLE_SUPPLIER,
                    counterparty_external_id="cp-supplier-1",
                    currency_code="RUB",
                    amount=Decimal("3200000.00"),
                    parent_customer_contract_external_id="ctr-customer-1",
                ),
                ContractDTO(
                    external_id="ctr-supplier-2",
                    number="ЕП-2026-022",
                    date=date(2026, 2, 12),
                    name="Аренда спецоборудования",
                    kind=ContractKind.SOLE_SUPPLIER,
                    counterparty_external_id="cp-supplier-2",
                    currency_code="RUB",
                    amount=Decimal("1450000.00"),
                    parent_customer_contract_external_id="ctr-customer-1",
                ),
                ContractDTO(
                    external_id="ctr-it-1",
                    number="ЕП-2026-031",
                    date=date(2026, 3, 10),
                    name="Лицензии аналитической платформы",
                    kind=ContractKind.SOLE_SUPPLIER,
                    counterparty_external_id="cp-it",
                    currency_code="USD",
                    amount=Decimal("18000.00"),
                    manual_exchange_rate=Decimal("92.5000"),
                    parent_customer_contract_external_id="ctr-customer-1",
                ),
            ],
            additional_agreements=[
                AdditionalAgreementDTO(
                    external_id="agr-supplier-1-1",
                    contract_external_id="ctr-supplier-1",
                    number="ДС-1",
                    date=date(2026, 3, 1),
                    amount=Decimal("450000.00"),
                    currency_code="RUB",
                ),
                AdditionalAgreementDTO(
                    external_id="agr-supplier-1-2",
                    contract_external_id="ctr-supplier-1",
                    number="ДС-2",
                    date=date(2026, 4, 5),
                    amount=Decimal("210000.00"),
                    currency_code="RUB",
                ),
                AdditionalAgreementDTO(
                    external_id="agr-it-1-1",
                    contract_external_id="ctr-it-1",
                    number="ДС-1",
                    date=date(2026, 4, 12),
                    amount=Decimal("2500.00"),
                    currency_code="USD",
                ),
            ],
            payment_facts=[
                PaymentFactDTO(
                    external_id="pay-0001",
                    organization_external_id="org-gladiolus",
                    date=date(2026, 2, 20),
                    account="51",
                    direction=PaymentDirection.OUTFLOW,
                    accounting_kind=AccountingKind.BU,
                    article_external_id="dds-ops",
                    counterparty_external_id="cp-supplier-1",
                    contract_external_id="ctr-supplier-1",
                    amount=Decimal("800000.00"),
                    currency_code="RUB",
                    comment="Оплата этапа монтажа",
                ),
                PaymentFactDTO(
                    external_id="pay-0001",
                    organization_external_id="org-gladiolus",
                    date=date(2026, 2, 20),
                    account="51",
                    direction=PaymentDirection.OUTFLOW,
                    accounting_kind=AccountingKind.NU,
                    article_external_id="dds-ops",
                    counterparty_external_id="cp-supplier-1",
                    contract_external_id="ctr-supplier-1",
                    amount=Decimal("760000.00"),
                    currency_code="RUB",
                    comment="НУ отличается из-за признания расходов",
                ),
                PaymentFactDTO(
                    external_id="pay-0002",
                    organization_external_id="org-gladiolus",
                    date=date(2026, 3, 15),
                    account="50",
                    direction=PaymentDirection.OUTFLOW,
                    accounting_kind=AccountingKind.BU,
                    article_external_id="dds-rent",
                    counterparty_external_id="cp-supplier-2",
                    contract_external_id="ctr-supplier-2",
                    amount=Decimal("180000.00"),
                    currency_code="RUB",
                    comment="Наличный расход по аренде",
                ),
                PaymentFactDTO(
                    external_id="pay-0003",
                    organization_external_id="org-gladiolus",
                    date=date(2026, 4, 3),
                    account="51",
                    direction=PaymentDirection.OUTFLOW,
                    accounting_kind=AccountingKind.BU,
                    article_external_id="dds-vgo",
                    counterparty_external_id="cp-group",
                    amount=Decimal("350000.00"),
                    currency_code="RUB",
                    comment="Оборот ВГО",
                ),
            ],
        )
